# Generated by Django 4.1.1 on 2023-04-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('corporation_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('helpline', models.PositiveBigIntegerField()),
            ],
        ),
    ]
