# Generated by Django 4.1.1 on 2023-04-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('office_number', models.PositiveBigIntegerField()),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporations.corporation')),
            ],
        ),
    ]
