# Generated by Django 4.1.1 on 2023-04-12 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0002_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('office_number', models.PositiveBigIntegerField()),
                ('email_id', models.EmailField(blank=True, max_length=50, unique=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporations.corporation')),
            ],
        ),
    ]
