# Generated by Django 4.1.1 on 2023-04-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0003_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporations.zone')),
            ],
        ),
    ]
