# Generated by Django 4.1.1 on 2023-04-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0004_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporations.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporations.department')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporations.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('desi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporations.staff')),
            ],
        ),
    ]
