# Generated by Django 4.1.1 on 2023-04-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0006_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('bank_city', models.CharField(max_length=50)),
            ],
        ),
    ]
