# Generated by Django 4.1.1 on 2023-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0008_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporation',
            name='corporation_id',
        ),
        migrations.AlterField(
            model_name='corporation',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
